# -*- coding: utf-8 -*-
"""test-github.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YPFvwVThWSnNZNYcXoIjWVtXkN79i888
"""

def sum(i,j):
  return i+j

